language: generic
dist: bionic

sudo: required

services:
  - docker

notifications:
  email: false

env:
  - OTP_VERSION=23.3

cache:
  directories:
    - docker-otp-23.3

before_install:
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --debug --registry-mirror=https://mirror.gcr.io"'
  - sudo service docker restart
  - docker system info
  -
    if [ -e "docker-otp-${OTP_VERSION}/image.tar" ]; then
      docker load -i "docker-otp-${OTP_VERSION}/image.tar";
    else
      docker build -t docker-otp-${OTP_VERSION} -f priv/Dockerfile --build-arg OTP_VERSION=${OTP_VERSION} priv;
      mkdir -p "docker-otp-${OTP_VERSION}"; docker save -o "docker-otp-${OTP_VERSION}/image.tar" docker-otp-${OTP_VERSION};
    fi

script:
  - docker run -v `pwd`:/build/libsodium docker-otp-${OTP_VERSION} sh -c 'cd libsodium && CC=clang-3.8 CXX=clang++-3.8 make tests'
